spring.application.name=pizzarianapoli

server.port=8080
spring.datasource.url=sqlserver://localhost:1433;databaseName=pizzarianapolidb;integratedSecurity=false;encrypt=false;trustServerCertificate=true
